bin(vmrss): handle invalid pid

diff --git a/bin/vmrss b/bin/vmrss
--- a/bin/vmrss
+++ b/bin/vmrss
@@ -5,6 +5,11 @@ if [[ $# -eq 0 ]]; then
     exit 1
 fi
 
+if ! ps -p $1 &>/dev/null; then
+    echo "error: invalid process ID"
+    exit 1
+fi
+
 # $1= pid
 print_vmrss() {
     res=(${(@s: :):-$(ps -p $1 -o comm=,pid=,rss=)})
